# Generated by Django 5.0.6 on 2024-06-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_mainmodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='key',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
