# Generated by Django 5.0.6 on 2024-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_mainmodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='data',
            field=models.TextField(),
        ),
    ]
