# Generated by Django 5.0.6 on 2024-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_mainmodel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
