# Generated by Django 4.2.15 on 2024-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_mainmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
